FROM arm32v7/python:3.7-slim-buster

WORKDIR /app
ADD ./test_image.JPG .

COPY requirements.txt ./
RUN pip install -r requirements.txt

EXPOSE 443

COPY . .

CMD [ "python3", "-u", "./main.py" ]