FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build-env

WORKDIR /app

RUN pip install ptvsd==4.1.3
COPY requirements.txt ./
RUN pip install -r requirements.txt

EXPOSE 443

COPY . .

CMD [ "python3", "-u", "./main.py" ]